actions:
  1:
    action: delete_indices
    description: >-
      Excluir índices. Descubra quais excluir limitando primeiro a lista a 
      índices prefixados por logstash. Em seguida, filtre-os ainda mais para evitar a 
      exclusão de qualquer coisa menor que o número de dias especificado por unit_count. 
      Ignore o erro se o filtro não resultar em uma lista acionável de índices 
      (ignore_empty_list) e saia de forma limpa.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 2
