# Dockerfile
#FROM node:18-alpine

# Set the working directory
#WORKDIR /app

# Copy package.json and package-lock.json
#COPY package*.json ./

# Install dependencies
#RUN npm install

# Copy application code
#COPY . .

# Expose the port
#EXPOSE 80

# Start the application
#CMD ["npm", "start"]

#FROM registry.ctn.prevnet/library/node:18.12.0-alpine as build
#FROM node:18.12.0-alpine as build
USER root
ENV NPM_CONFIG_PREFIX=/tmp/.npm HOME=/tmp CI=false

WORKDIR /app
COPY . .
RUN npm install
#RUN npm run dev
#RUN npm run build

FROM nginx:1.21-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
