services:

  app-ref-spring:
    container_name: docker-elk-ref-spring
    build:
      context: .
    ports:
      - '8080:8080'
      - '443:443'
    environment:
      - ELASTIC_APM_SERVER_URL=http://apm-server:8200
#    networks:
#      - elk

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'aplicacao-referencia'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
#    networks:
#      - elk

volumes:
  my-db:

#networks:
#  elk:
#    name: docker-elk_elk
#    external: true